# Generated by Django 2.2 on 2023-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_user_high_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='/static/codingbearblack.png', max_length=255, null=True),
        ),
    ]
