# Generated by Django 2.2 on 2023-04-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20230420_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='/static/codingbear.png', max_length=255, null=True),
        ),
    ]
