# Generated by Django 2.2 on 2023-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20230420_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='/static/profile.png', max_length=255, null=True),
        ),
    ]
